export const avatar = index => {
  const avatarArray = [
    'Avatars/avatar--yellow_bob@2x.png',
    'Avatars/avatar--yellow_curly@2x.png',
    'Avatars/avatar--yellow_goatee@2x.png',
    'Avatars/avatar--yellow_pixie@2x.png',
    'Avatars/avatar--yellow_wiffle@2x.png',
    'Avatars/avatar--brown_bob@2x.png',
    'Avatars/avatar--brown_curly@2x.png',
    'Avatars/avatar--brown_goatee@2x.png',
    'Avatars/avatar--brown_pixie@2x.png',
    'Avatars/avatar--brown_wiffle@2x.png',
    'Avatars/avatar--orange_bob@2x.png',
    'Avatars/avatar--orange_curly@2x.png',
    'Avatars/avatar--orange_goatee@2x.png',
    'Avatars/avatar--orange_pixie@2x.png',
    'Avatars/avatar--orange_wiffle@2x.png',
    'Avatars/avatar--black_bob@2x.png',
    'Avatars/avatar--black_curly@2x.png',
    'Avatars/avatar--black_goatee@2x.png',
    'Avatars/avatar--black_pixie@2x.png',
    'Avatars/avatar--black_wiffle@2x.png',
    'Avatars/avatar--gray_bob@2x.png',
    'Avatars/avatar--gray_curly@2x.png',
    'Avatars/avatar--gray_goatee@2x.png',
    'Avatars/avatar--gray_pixie@2x.png',
    'Avatars/avatar--gray_wiffle@2x.png',
    'Avatars/avatar--empty@2x.png',
    'Avatars/avatar--mask_dopecowpoke@2x.png',
    'Avatars/avatar--mask_humptyhump@2x.png',
    'Avatars/avatar--mask_mfdoom@2x.png',
    'Avatars/avatar--mask_monocle@2x.png',
    'Avatars/avatar--mask_shades@2x.png',
    'Avatars/avatar--mask_wizard@2x.png',
  ]
  return avatarArray[index]
}
